/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.datastreaming.framework.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class MerchantInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2680015902911641330L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MerchantInfo\",\"namespace\":\"com.datastreaming.framework.avro.model\",\"fields\":[{\"name\":\"merchantId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Merchant identifier\"},{\"name\":\"merchantName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Merchant name\"},{\"name\":\"category\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Merchant category\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MerchantInfo> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MerchantInfo> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MerchantInfo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MerchantInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MerchantInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MerchantInfo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MerchantInfo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MerchantInfo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MerchantInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Merchant identifier */
  private java.lang.String merchantId;
  /** Merchant name */
  private java.lang.String merchantName;
  /** Merchant category */
  private java.lang.String category;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MerchantInfo() {}

  /**
   * All-args constructor.
   * @param merchantId Merchant identifier
   * @param merchantName Merchant name
   * @param category Merchant category
   */
  public MerchantInfo(java.lang.String merchantId, java.lang.String merchantName, java.lang.String category) {
    this.merchantId = merchantId;
    this.merchantName = merchantName;
    this.category = category;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return merchantId;
    case 1: return merchantName;
    case 2: return category;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: merchantId = value$ != null ? value$.toString() : null; break;
    case 1: merchantName = value$ != null ? value$.toString() : null; break;
    case 2: category = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'merchantId' field.
   * @return Merchant identifier
   */
  public java.lang.String getMerchantId() {
    return merchantId;
  }


  /**
   * Sets the value of the 'merchantId' field.
   * Merchant identifier
   * @param value the value to set.
   */
  public void setMerchantId(java.lang.String value) {
    this.merchantId = value;
  }

  /**
   * Gets the value of the 'merchantName' field.
   * @return Merchant name
   */
  public java.lang.String getMerchantName() {
    return merchantName;
  }


  /**
   * Sets the value of the 'merchantName' field.
   * Merchant name
   * @param value the value to set.
   */
  public void setMerchantName(java.lang.String value) {
    this.merchantName = value;
  }

  /**
   * Gets the value of the 'category' field.
   * @return Merchant category
   */
  public java.lang.String getCategory() {
    return category;
  }


  /**
   * Sets the value of the 'category' field.
   * Merchant category
   * @param value the value to set.
   */
  public void setCategory(java.lang.String value) {
    this.category = value;
  }

  /**
   * Creates a new MerchantInfo RecordBuilder.
   * @return A new MerchantInfo RecordBuilder
   */
  public static com.datastreaming.framework.avro.model.MerchantInfo.Builder newBuilder() {
    return new com.datastreaming.framework.avro.model.MerchantInfo.Builder();
  }

  /**
   * Creates a new MerchantInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MerchantInfo RecordBuilder
   */
  public static com.datastreaming.framework.avro.model.MerchantInfo.Builder newBuilder(com.datastreaming.framework.avro.model.MerchantInfo.Builder other) {
    if (other == null) {
      return new com.datastreaming.framework.avro.model.MerchantInfo.Builder();
    } else {
      return new com.datastreaming.framework.avro.model.MerchantInfo.Builder(other);
    }
  }

  /**
   * Creates a new MerchantInfo RecordBuilder by copying an existing MerchantInfo instance.
   * @param other The existing instance to copy.
   * @return A new MerchantInfo RecordBuilder
   */
  public static com.datastreaming.framework.avro.model.MerchantInfo.Builder newBuilder(com.datastreaming.framework.avro.model.MerchantInfo other) {
    if (other == null) {
      return new com.datastreaming.framework.avro.model.MerchantInfo.Builder();
    } else {
      return new com.datastreaming.framework.avro.model.MerchantInfo.Builder(other);
    }
  }

  /**
   * RecordBuilder for MerchantInfo instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MerchantInfo>
    implements org.apache.avro.data.RecordBuilder<MerchantInfo> {

    /** Merchant identifier */
    private java.lang.String merchantId;
    /** Merchant name */
    private java.lang.String merchantName;
    /** Merchant category */
    private java.lang.String category;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.datastreaming.framework.avro.model.MerchantInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.merchantId)) {
        this.merchantId = data().deepCopy(fields()[0].schema(), other.merchantId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.merchantName)) {
        this.merchantName = data().deepCopy(fields()[1].schema(), other.merchantName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.category)) {
        this.category = data().deepCopy(fields()[2].schema(), other.category);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing MerchantInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.datastreaming.framework.avro.model.MerchantInfo other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.merchantId)) {
        this.merchantId = data().deepCopy(fields()[0].schema(), other.merchantId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.merchantName)) {
        this.merchantName = data().deepCopy(fields()[1].schema(), other.merchantName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.category)) {
        this.category = data().deepCopy(fields()[2].schema(), other.category);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'merchantId' field.
      * Merchant identifier
      * @return The value.
      */
    public java.lang.String getMerchantId() {
      return merchantId;
    }


    /**
      * Sets the value of the 'merchantId' field.
      * Merchant identifier
      * @param value The value of 'merchantId'.
      * @return This builder.
      */
    public com.datastreaming.framework.avro.model.MerchantInfo.Builder setMerchantId(java.lang.String value) {
      validate(fields()[0], value);
      this.merchantId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'merchantId' field has been set.
      * Merchant identifier
      * @return True if the 'merchantId' field has been set, false otherwise.
      */
    public boolean hasMerchantId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'merchantId' field.
      * Merchant identifier
      * @return This builder.
      */
    public com.datastreaming.framework.avro.model.MerchantInfo.Builder clearMerchantId() {
      merchantId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'merchantName' field.
      * Merchant name
      * @return The value.
      */
    public java.lang.String getMerchantName() {
      return merchantName;
    }


    /**
      * Sets the value of the 'merchantName' field.
      * Merchant name
      * @param value The value of 'merchantName'.
      * @return This builder.
      */
    public com.datastreaming.framework.avro.model.MerchantInfo.Builder setMerchantName(java.lang.String value) {
      validate(fields()[1], value);
      this.merchantName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'merchantName' field has been set.
      * Merchant name
      * @return True if the 'merchantName' field has been set, false otherwise.
      */
    public boolean hasMerchantName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'merchantName' field.
      * Merchant name
      * @return This builder.
      */
    public com.datastreaming.framework.avro.model.MerchantInfo.Builder clearMerchantName() {
      merchantName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'category' field.
      * Merchant category
      * @return The value.
      */
    public java.lang.String getCategory() {
      return category;
    }


    /**
      * Sets the value of the 'category' field.
      * Merchant category
      * @param value The value of 'category'.
      * @return This builder.
      */
    public com.datastreaming.framework.avro.model.MerchantInfo.Builder setCategory(java.lang.String value) {
      validate(fields()[2], value);
      this.category = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'category' field has been set.
      * Merchant category
      * @return True if the 'category' field has been set, false otherwise.
      */
    public boolean hasCategory() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'category' field.
      * Merchant category
      * @return This builder.
      */
    public com.datastreaming.framework.avro.model.MerchantInfo.Builder clearCategory() {
      category = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MerchantInfo build() {
      try {
        MerchantInfo record = new MerchantInfo();
        record.merchantId = fieldSetFlags()[0] ? this.merchantId : (java.lang.String) defaultValue(fields()[0]);
        record.merchantName = fieldSetFlags()[1] ? this.merchantName : (java.lang.String) defaultValue(fields()[1]);
        record.category = fieldSetFlags()[2] ? this.category : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MerchantInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<MerchantInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MerchantInfo>
    READER$ = (org.apache.avro.io.DatumReader<MerchantInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.merchantId);

    out.writeString(this.merchantName);

    if (this.category == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.category);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.merchantId = in.readString();

      this.merchantName = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.category = null;
      } else {
        this.category = in.readString();
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.merchantId = in.readString();
          break;

        case 1:
          this.merchantName = in.readString();
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.category = null;
          } else {
            this.category = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










