/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.datastreaming.framework.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class MessageMetadata extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1636827067724159697L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MessageMetadata\",\"namespace\":\"com.datastreaming.framework.avro.model\",\"fields\":[{\"name\":\"processingTime\",\"type\":[\"null\",\"long\"],\"doc\":\"Message processing timestamp\",\"default\":null},{\"name\":\"retryCount\",\"type\":[\"null\",\"int\"],\"doc\":\"Number of retry attempts\",\"default\":null},{\"name\":\"errorMessage\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Error message if processing failed\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MessageMetadata> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MessageMetadata> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MessageMetadata> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MessageMetadata> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MessageMetadata> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MessageMetadata to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MessageMetadata from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MessageMetadata instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MessageMetadata fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Message processing timestamp */
  private java.lang.Long processingTime;
  /** Number of retry attempts */
  private java.lang.Integer retryCount;
  /** Error message if processing failed */
  private java.lang.String errorMessage;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MessageMetadata() {}

  /**
   * All-args constructor.
   * @param processingTime Message processing timestamp
   * @param retryCount Number of retry attempts
   * @param errorMessage Error message if processing failed
   */
  public MessageMetadata(java.lang.Long processingTime, java.lang.Integer retryCount, java.lang.String errorMessage) {
    this.processingTime = processingTime;
    this.retryCount = retryCount;
    this.errorMessage = errorMessage;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return processingTime;
    case 1: return retryCount;
    case 2: return errorMessage;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: processingTime = (java.lang.Long)value$; break;
    case 1: retryCount = (java.lang.Integer)value$; break;
    case 2: errorMessage = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'processingTime' field.
   * @return Message processing timestamp
   */
  public java.lang.Long getProcessingTime() {
    return processingTime;
  }


  /**
   * Sets the value of the 'processingTime' field.
   * Message processing timestamp
   * @param value the value to set.
   */
  public void setProcessingTime(java.lang.Long value) {
    this.processingTime = value;
  }

  /**
   * Gets the value of the 'retryCount' field.
   * @return Number of retry attempts
   */
  public java.lang.Integer getRetryCount() {
    return retryCount;
  }


  /**
   * Sets the value of the 'retryCount' field.
   * Number of retry attempts
   * @param value the value to set.
   */
  public void setRetryCount(java.lang.Integer value) {
    this.retryCount = value;
  }

  /**
   * Gets the value of the 'errorMessage' field.
   * @return Error message if processing failed
   */
  public java.lang.String getErrorMessage() {
    return errorMessage;
  }


  /**
   * Sets the value of the 'errorMessage' field.
   * Error message if processing failed
   * @param value the value to set.
   */
  public void setErrorMessage(java.lang.String value) {
    this.errorMessage = value;
  }

  /**
   * Creates a new MessageMetadata RecordBuilder.
   * @return A new MessageMetadata RecordBuilder
   */
  public static com.datastreaming.framework.avro.model.MessageMetadata.Builder newBuilder() {
    return new com.datastreaming.framework.avro.model.MessageMetadata.Builder();
  }

  /**
   * Creates a new MessageMetadata RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MessageMetadata RecordBuilder
   */
  public static com.datastreaming.framework.avro.model.MessageMetadata.Builder newBuilder(com.datastreaming.framework.avro.model.MessageMetadata.Builder other) {
    if (other == null) {
      return new com.datastreaming.framework.avro.model.MessageMetadata.Builder();
    } else {
      return new com.datastreaming.framework.avro.model.MessageMetadata.Builder(other);
    }
  }

  /**
   * Creates a new MessageMetadata RecordBuilder by copying an existing MessageMetadata instance.
   * @param other The existing instance to copy.
   * @return A new MessageMetadata RecordBuilder
   */
  public static com.datastreaming.framework.avro.model.MessageMetadata.Builder newBuilder(com.datastreaming.framework.avro.model.MessageMetadata other) {
    if (other == null) {
      return new com.datastreaming.framework.avro.model.MessageMetadata.Builder();
    } else {
      return new com.datastreaming.framework.avro.model.MessageMetadata.Builder(other);
    }
  }

  /**
   * RecordBuilder for MessageMetadata instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MessageMetadata>
    implements org.apache.avro.data.RecordBuilder<MessageMetadata> {

    /** Message processing timestamp */
    private java.lang.Long processingTime;
    /** Number of retry attempts */
    private java.lang.Integer retryCount;
    /** Error message if processing failed */
    private java.lang.String errorMessage;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.datastreaming.framework.avro.model.MessageMetadata.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.processingTime)) {
        this.processingTime = data().deepCopy(fields()[0].schema(), other.processingTime);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.retryCount)) {
        this.retryCount = data().deepCopy(fields()[1].schema(), other.retryCount);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[2].schema(), other.errorMessage);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing MessageMetadata instance
     * @param other The existing instance to copy.
     */
    private Builder(com.datastreaming.framework.avro.model.MessageMetadata other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.processingTime)) {
        this.processingTime = data().deepCopy(fields()[0].schema(), other.processingTime);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.retryCount)) {
        this.retryCount = data().deepCopy(fields()[1].schema(), other.retryCount);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[2].schema(), other.errorMessage);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'processingTime' field.
      * Message processing timestamp
      * @return The value.
      */
    public java.lang.Long getProcessingTime() {
      return processingTime;
    }


    /**
      * Sets the value of the 'processingTime' field.
      * Message processing timestamp
      * @param value The value of 'processingTime'.
      * @return This builder.
      */
    public com.datastreaming.framework.avro.model.MessageMetadata.Builder setProcessingTime(java.lang.Long value) {
      validate(fields()[0], value);
      this.processingTime = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'processingTime' field has been set.
      * Message processing timestamp
      * @return True if the 'processingTime' field has been set, false otherwise.
      */
    public boolean hasProcessingTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'processingTime' field.
      * Message processing timestamp
      * @return This builder.
      */
    public com.datastreaming.framework.avro.model.MessageMetadata.Builder clearProcessingTime() {
      processingTime = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'retryCount' field.
      * Number of retry attempts
      * @return The value.
      */
    public java.lang.Integer getRetryCount() {
      return retryCount;
    }


    /**
      * Sets the value of the 'retryCount' field.
      * Number of retry attempts
      * @param value The value of 'retryCount'.
      * @return This builder.
      */
    public com.datastreaming.framework.avro.model.MessageMetadata.Builder setRetryCount(java.lang.Integer value) {
      validate(fields()[1], value);
      this.retryCount = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'retryCount' field has been set.
      * Number of retry attempts
      * @return True if the 'retryCount' field has been set, false otherwise.
      */
    public boolean hasRetryCount() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'retryCount' field.
      * Number of retry attempts
      * @return This builder.
      */
    public com.datastreaming.framework.avro.model.MessageMetadata.Builder clearRetryCount() {
      retryCount = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'errorMessage' field.
      * Error message if processing failed
      * @return The value.
      */
    public java.lang.String getErrorMessage() {
      return errorMessage;
    }


    /**
      * Sets the value of the 'errorMessage' field.
      * Error message if processing failed
      * @param value The value of 'errorMessage'.
      * @return This builder.
      */
    public com.datastreaming.framework.avro.model.MessageMetadata.Builder setErrorMessage(java.lang.String value) {
      validate(fields()[2], value);
      this.errorMessage = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'errorMessage' field has been set.
      * Error message if processing failed
      * @return True if the 'errorMessage' field has been set, false otherwise.
      */
    public boolean hasErrorMessage() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'errorMessage' field.
      * Error message if processing failed
      * @return This builder.
      */
    public com.datastreaming.framework.avro.model.MessageMetadata.Builder clearErrorMessage() {
      errorMessage = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MessageMetadata build() {
      try {
        MessageMetadata record = new MessageMetadata();
        record.processingTime = fieldSetFlags()[0] ? this.processingTime : (java.lang.Long) defaultValue(fields()[0]);
        record.retryCount = fieldSetFlags()[1] ? this.retryCount : (java.lang.Integer) defaultValue(fields()[1]);
        record.errorMessage = fieldSetFlags()[2] ? this.errorMessage : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MessageMetadata>
    WRITER$ = (org.apache.avro.io.DatumWriter<MessageMetadata>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MessageMetadata>
    READER$ = (org.apache.avro.io.DatumReader<MessageMetadata>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.processingTime == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.processingTime);
    }

    if (this.retryCount == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.retryCount);
    }

    if (this.errorMessage == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.errorMessage);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.processingTime = null;
      } else {
        this.processingTime = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.retryCount = null;
      } else {
        this.retryCount = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.errorMessage = null;
      } else {
        this.errorMessage = in.readString();
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.processingTime = null;
          } else {
            this.processingTime = in.readLong();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.retryCount = null;
          } else {
            this.retryCount = in.readInt();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.errorMessage = null;
          } else {
            this.errorMessage = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










