/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.datastreaming.framework.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ProcessingInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 703712371545864792L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProcessingInfo\",\"namespace\":\"com.datastreaming.framework.avro.model\",\"fields\":[{\"name\":\"processedAt\",\"type\":[\"null\",\"long\"],\"doc\":\"Processing timestamp\",\"default\":null},{\"name\":\"processedBy\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Processing system identifier\",\"default\":null},{\"name\":\"correlationId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Correlation ID for tracking\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ProcessingInfo> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProcessingInfo> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProcessingInfo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProcessingInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProcessingInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProcessingInfo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProcessingInfo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProcessingInfo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProcessingInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Processing timestamp */
  private java.lang.Long processedAt;
  /** Processing system identifier */
  private java.lang.String processedBy;
  /** Correlation ID for tracking */
  private java.lang.String correlationId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProcessingInfo() {}

  /**
   * All-args constructor.
   * @param processedAt Processing timestamp
   * @param processedBy Processing system identifier
   * @param correlationId Correlation ID for tracking
   */
  public ProcessingInfo(java.lang.Long processedAt, java.lang.String processedBy, java.lang.String correlationId) {
    this.processedAt = processedAt;
    this.processedBy = processedBy;
    this.correlationId = correlationId;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return processedAt;
    case 1: return processedBy;
    case 2: return correlationId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: processedAt = (java.lang.Long)value$; break;
    case 1: processedBy = value$ != null ? value$.toString() : null; break;
    case 2: correlationId = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'processedAt' field.
   * @return Processing timestamp
   */
  public java.lang.Long getProcessedAt() {
    return processedAt;
  }


  /**
   * Sets the value of the 'processedAt' field.
   * Processing timestamp
   * @param value the value to set.
   */
  public void setProcessedAt(java.lang.Long value) {
    this.processedAt = value;
  }

  /**
   * Gets the value of the 'processedBy' field.
   * @return Processing system identifier
   */
  public java.lang.String getProcessedBy() {
    return processedBy;
  }


  /**
   * Sets the value of the 'processedBy' field.
   * Processing system identifier
   * @param value the value to set.
   */
  public void setProcessedBy(java.lang.String value) {
    this.processedBy = value;
  }

  /**
   * Gets the value of the 'correlationId' field.
   * @return Correlation ID for tracking
   */
  public java.lang.String getCorrelationId() {
    return correlationId;
  }


  /**
   * Sets the value of the 'correlationId' field.
   * Correlation ID for tracking
   * @param value the value to set.
   */
  public void setCorrelationId(java.lang.String value) {
    this.correlationId = value;
  }

  /**
   * Creates a new ProcessingInfo RecordBuilder.
   * @return A new ProcessingInfo RecordBuilder
   */
  public static com.datastreaming.framework.avro.model.ProcessingInfo.Builder newBuilder() {
    return new com.datastreaming.framework.avro.model.ProcessingInfo.Builder();
  }

  /**
   * Creates a new ProcessingInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProcessingInfo RecordBuilder
   */
  public static com.datastreaming.framework.avro.model.ProcessingInfo.Builder newBuilder(com.datastreaming.framework.avro.model.ProcessingInfo.Builder other) {
    if (other == null) {
      return new com.datastreaming.framework.avro.model.ProcessingInfo.Builder();
    } else {
      return new com.datastreaming.framework.avro.model.ProcessingInfo.Builder(other);
    }
  }

  /**
   * Creates a new ProcessingInfo RecordBuilder by copying an existing ProcessingInfo instance.
   * @param other The existing instance to copy.
   * @return A new ProcessingInfo RecordBuilder
   */
  public static com.datastreaming.framework.avro.model.ProcessingInfo.Builder newBuilder(com.datastreaming.framework.avro.model.ProcessingInfo other) {
    if (other == null) {
      return new com.datastreaming.framework.avro.model.ProcessingInfo.Builder();
    } else {
      return new com.datastreaming.framework.avro.model.ProcessingInfo.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProcessingInfo instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProcessingInfo>
    implements org.apache.avro.data.RecordBuilder<ProcessingInfo> {

    /** Processing timestamp */
    private java.lang.Long processedAt;
    /** Processing system identifier */
    private java.lang.String processedBy;
    /** Correlation ID for tracking */
    private java.lang.String correlationId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.datastreaming.framework.avro.model.ProcessingInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.processedAt)) {
        this.processedAt = data().deepCopy(fields()[0].schema(), other.processedAt);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.processedBy)) {
        this.processedBy = data().deepCopy(fields()[1].schema(), other.processedBy);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.correlationId)) {
        this.correlationId = data().deepCopy(fields()[2].schema(), other.correlationId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ProcessingInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.datastreaming.framework.avro.model.ProcessingInfo other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.processedAt)) {
        this.processedAt = data().deepCopy(fields()[0].schema(), other.processedAt);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.processedBy)) {
        this.processedBy = data().deepCopy(fields()[1].schema(), other.processedBy);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.correlationId)) {
        this.correlationId = data().deepCopy(fields()[2].schema(), other.correlationId);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'processedAt' field.
      * Processing timestamp
      * @return The value.
      */
    public java.lang.Long getProcessedAt() {
      return processedAt;
    }


    /**
      * Sets the value of the 'processedAt' field.
      * Processing timestamp
      * @param value The value of 'processedAt'.
      * @return This builder.
      */
    public com.datastreaming.framework.avro.model.ProcessingInfo.Builder setProcessedAt(java.lang.Long value) {
      validate(fields()[0], value);
      this.processedAt = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'processedAt' field has been set.
      * Processing timestamp
      * @return True if the 'processedAt' field has been set, false otherwise.
      */
    public boolean hasProcessedAt() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'processedAt' field.
      * Processing timestamp
      * @return This builder.
      */
    public com.datastreaming.framework.avro.model.ProcessingInfo.Builder clearProcessedAt() {
      processedAt = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'processedBy' field.
      * Processing system identifier
      * @return The value.
      */
    public java.lang.String getProcessedBy() {
      return processedBy;
    }


    /**
      * Sets the value of the 'processedBy' field.
      * Processing system identifier
      * @param value The value of 'processedBy'.
      * @return This builder.
      */
    public com.datastreaming.framework.avro.model.ProcessingInfo.Builder setProcessedBy(java.lang.String value) {
      validate(fields()[1], value);
      this.processedBy = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'processedBy' field has been set.
      * Processing system identifier
      * @return True if the 'processedBy' field has been set, false otherwise.
      */
    public boolean hasProcessedBy() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'processedBy' field.
      * Processing system identifier
      * @return This builder.
      */
    public com.datastreaming.framework.avro.model.ProcessingInfo.Builder clearProcessedBy() {
      processedBy = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'correlationId' field.
      * Correlation ID for tracking
      * @return The value.
      */
    public java.lang.String getCorrelationId() {
      return correlationId;
    }


    /**
      * Sets the value of the 'correlationId' field.
      * Correlation ID for tracking
      * @param value The value of 'correlationId'.
      * @return This builder.
      */
    public com.datastreaming.framework.avro.model.ProcessingInfo.Builder setCorrelationId(java.lang.String value) {
      validate(fields()[2], value);
      this.correlationId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'correlationId' field has been set.
      * Correlation ID for tracking
      * @return True if the 'correlationId' field has been set, false otherwise.
      */
    public boolean hasCorrelationId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'correlationId' field.
      * Correlation ID for tracking
      * @return This builder.
      */
    public com.datastreaming.framework.avro.model.ProcessingInfo.Builder clearCorrelationId() {
      correlationId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProcessingInfo build() {
      try {
        ProcessingInfo record = new ProcessingInfo();
        record.processedAt = fieldSetFlags()[0] ? this.processedAt : (java.lang.Long) defaultValue(fields()[0]);
        record.processedBy = fieldSetFlags()[1] ? this.processedBy : (java.lang.String) defaultValue(fields()[1]);
        record.correlationId = fieldSetFlags()[2] ? this.correlationId : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProcessingInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProcessingInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProcessingInfo>
    READER$ = (org.apache.avro.io.DatumReader<ProcessingInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.processedAt == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.processedAt);
    }

    if (this.processedBy == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.processedBy);
    }

    if (this.correlationId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.correlationId);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.processedAt = null;
      } else {
        this.processedAt = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.processedBy = null;
      } else {
        this.processedBy = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.correlationId = null;
      } else {
        this.correlationId = in.readString();
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.processedAt = null;
          } else {
            this.processedAt = in.readLong();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.processedBy = null;
          } else {
            this.processedBy = in.readString();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.correlationId = null;
          } else {
            this.correlationId = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










