/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.datastreaming.framework.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum TransactionType implements org.apache.avro.generic.GenericEnumSymbol<TransactionType> {
  DEBIT, CREDIT, TRANSFER, PAYMENT, REFUND  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TransactionType\",\"namespace\":\"com.datastreaming.framework.avro.model\",\"symbols\":[\"DEBIT\",\"CREDIT\",\"TRANSFER\",\"PAYMENT\",\"REFUND\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
