/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.datastreaming.framework.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum TransactionStatus implements org.apache.avro.generic.GenericEnumSymbol<TransactionStatus> {
  PENDING, COMPLETED, FAILED, CANCELLED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TransactionStatus\",\"namespace\":\"com.datastreaming.framework.avro.model\",\"symbols\":[\"PENDING\",\"COMPLETED\",\"FAILED\",\"CANCELLED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
